export const mockDiffFileList: FileDifference[] = [
  {
    id: '1',
    fileName: 'root',
    isDirectory: true,
    difference: 'conflict',
    resolution: 'toRight',
    source: {
      key: 'source-root',
      fileName: 'root',
      size: 0,
      timestamp: new Date('2025-08-10 10:00'),
      filePath: '/root',
      relativePath: '',
      isDirectory: true,
    },
    destination: {
      key: 'target-root',
      fileName: 'root',
      size: 0,
      timestamp: new Date('2025-08-12 12:00'),
      filePath: '/root',
      relativePath: '',
      isDirectory: true,
    },
    children: [
      {
        id: '1-1',
        fileName: 'only_on_left.txt',
        isDirectory: false,
        difference: 'onlySource',
        resolution: 'toRight',
        source: {
          key: 'source-only_on_left.txt',
          fileName: 'only_on_left.txt',
          size: 1024,
          timestamp: new Date('2025-07-01 09:00'),
          filePath: '/root/only_on_left.txt',
          relativePath: 'only_on_left.txt',
          isDirectory: false,
        },
        destination: null,
        children: [],
      },
      {
        id: '1-2',
        fileName: 'only_on_right.log',
        isDirectory: false,
        difference: 'onlyDest',
        resolution: 'toRight',
        source: null,
        destination: {
          key: 'target-only_on_right.log',
          fileName: 'only_on_right.log',
          size: 2048,
          timestamp: new Date('2025-07-02 11:00'),
          filePath: '/root/only_on_right.log',
          relativePath: 'only_on_right.log',
          isDirectory: false,
        },
        children: [],
      },
      {
        id: '1-3',
        fileName: 'conflict_dir',
        isDirectory: true,
        difference: 'conflict',
        resolution: 'toRight',
        source: {
          key: 'source-conflict_dir',
          fileName: 'conflict_dir',
          size: 0,
          timestamp: new Date('2025-06-20 08:00'),
          filePath: '/root/conflict_dir',
          relativePath: 'conflict_dir',
          isDirectory: true,
        },
        destination: {
          key: 'target-conflict_dir',
          fileName: 'conflict_dir',
          size: 0,
          timestamp: new Date('2025-06-21 08:30'),
          filePath: '/root/conflict_dir',
          relativePath: 'conflict_dir',
          isDirectory: true,
        },
        children: [
          {
            id: '1-3-1',
            fileName: 'nested_left_only.md',
            isDirectory: false,
            difference: 'onlySource',
            resolution: 'toRight',
            source: {
              key: 'source-nested_left_only.md',
              fileName: 'nested_left_only.md',
              size: 512,
              timestamp: new Date('2025-05-05 05:05'),
              filePath: '/root/conflict_dir/nested_left_only.md',
              relativePath: 'conflict_dir/nested_left_only.md',
              isDirectory: false,
            },
            destination: null,
            children: [],
          },
          {
            id: '1-3-2',
            fileName: 'nested_both.txt',
            isDirectory: false,
            difference: 'conflict',
            resolution: 'toRight',
            source: {
              key: 'source-nested_both.txt',
              fileName: 'nested_both.txt',
              size: 300,
              timestamp: new Date('2025-05-06 06:06'),
              filePath: '/root/conflict_dir/nested_both.txt',
              relativePath: 'conflict_dir/nested_both.txt',
              isDirectory: false,
            },
            destination: {
              key: 'target-nested_both.txt',
              fileName: 'nested_both.txt',
              size: 320,
              timestamp: new Date('2025-05-07 07:07'),
              filePath: '/root/conflict_dir/nested_both.txt',
              relativePath: 'conflict_dir/nested_both.txt',
              isDirectory: false,
            },
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: '2',
    fileName: 'another_root',
    isDirectory: true,
    difference: 'onlyDest',
    resolution: 'toRight',
    source: null,
    destination: {
      key: 'target-another_root',
      fileName: 'another_root',
      size: 0,
      timestamp: new Date('2025-08-01 01:01'),
      filePath: '/another_root',
      relativePath: '',
      isDirectory: true,
    },
    children: [
      {
        id: '2-1',
        fileName: 'right_only_file.jpg',
        isDirectory: false,
        difference: 'onlyDest',
        resolution: 'toRight',
        source: null,
        destination: {
          key: 'target-right_only_file.jpg',
          fileName: 'right_only_file.jpg',
          size: 4096,
          timestamp: new Date('2025-04-04 04:04'),
          filePath: '/another_root/right_only_file.jpg',
          relativePath: 'right_only_file.jpg',
          isDirectory: false,
        },
        children: [],
      },
    ],
  },
]
